username: GitHub-CI
icon_url: https://octodex.github.com/images/mona-the-rivetertocat.png

text: Triggered via {{eventName}} by {{actor}} on <{{repositoryUrl}}|{{repositoryName}}>

fallback: |-
  [GitHub] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}

fields:
  - title: Job Details
    value: "{{#each jobSteps}}{{icon this.outcome}} {{@key}}\n{{/each}}"
    short: true
  - title: Git Ref
    value: "{{ref}} ({{refType}})"
    short: true
  - title: Job Status {{icon jobStatus}}
    value: "{{jobStatus}}"
    short: true


footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}

colors:
  success: 'good'
  failure: 'danger'
  cancelled: 'warning'
  default: '#7D3C98'

icons:
  success: ':white_check_mark:'
  failure: ':grimacing:'
  cancelled: ':x:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'