name: Deploy to prod


on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
        options: ['main']
        default: 'main'
      release-version:
        description: 'Release version tag'
        required: true
  release:
    types:
      - released
      - created
      - published

permissions: write-all

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  prod-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout latest release tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "npm install"
        run: |
          echo "npm install"
          npm install

      - name: "npm build"
        run: |
          echo "npm build"
          npm run compile
          npm run dist

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          config: .github/slack.yml

          channel: '#cicd'
        if: always()

